name = "ada-deposit-withdraw/ada-withdraw"
version = "0.0.0"
compiler = "v1.0.29-alpha"
plutus = "v2"
license = "Apache-2.0"
description = "Aiken contracts for project 'ada-deposit-withdraw/ada-withdraw'"

[repository]
user = "aiken-lang"
project = "ada-deposit-withdraw"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.9.0"
source = "github"
